CC=gcc
FLAGS=-O0 -w

all:
	$(CC) -o measureRAMaccess measureRAMaccess.c $(FLAGS)
	$(CC) -o measureRAMbandwidth measureRAMbandwidth.c $(FLAGS)
	$(CC) -o measurePFtime measurePFtime.c $(FLAGS)
clean:
	rm *csv
