#!/bin/bash

BS=4K
RESULTFILE="resultsRanread.csv"

if [ -z $RESULTFILE ]; then
	rm $RESULTFILE
fi

echo "[*]Turning off all but one CPU core"
sleep 1
for i in `seq 1 3`; do
	echo 0|sudo tee /sys/devices/system/cpu/cpu$i/online
done

echo "file.size,cycles" > $RESULTFILE
for j in `seq 10 21`; do
	FILENAME=$((1024*(2**j)))
	echo "[+] Creating a $FILENAME byte file..."
	dd bs=$BS count=$((2**($j-2))) if=/dev/urandom of=$FILENAME 2> /dev/null
	echo "[+] Gathering time data..."
    echo 3 |sudo tee /proc/sys/vm/drop_caches
	./measureRantime $FILENAME
    echo 3 |sudo tee /proc/sys/vm/drop_caches
	echo "[+] Cleaning up..."
	rm $FILENAME
	echo "********************************************"
done

echo "[*] Turning CPU cores back on"
sleep 1
for i in `seq 1 3`; do
		echo 1|sudo tee /sys/devices/system/cpu/cpu$i/online
done

echo "[!] Job's done! Results are in $RESULTFILE"
